# Generated by Django 3.0.5 on 2020-05-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffilliateProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image_url', models.TextField()),
                ('redirect_url', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
            ],
        ),
    ]
