# Form field names
LOGIN_FORM_EMAIL_FIELD_NAME = 'email'
LOGIN_FORM_PASSWORD_FIELD_NAME = 'password'

REGISTER_FORM_FIRST_NAME = 'first_name'
REGISTER_FORM_LAST_NAME = 'last_name'
REGISTER_FORM_EMAIL = 'email'
REGISTER_FORM_PASSWORD = 'password'
REGISTER_FORM_PASSWORD2 = 'password2'


# MESSAGES


#SESSION_KEYS

SESSION_WORKSPACE_KEY_NAME ='workspace_id'