# Generated by Django 3.0.5 on 2020-05-14 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200514_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='tasks',
            field=models.ManyToManyField(null=True, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='CycleTaskAssociation',
        ),
    ]
