# Generated by Django 3.0.5 on 2020-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200514_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
