# Generated by Django 3.0.5 on 2020-05-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200524_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
