# Generated by Django 3.0.5 on 2020-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200527_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleHistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('done_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
        ),
    ]
